export enum ScoringTypes {
  FIRST_RECORDING = 'FIRST_RECORDING',
  FIRST_THEME = 'FIRST_THEME',
  REGISTRATION = 'REGISTRATION',
  FINISHED_THEME = 'FINISHED_THEME',
  RECOMMENDATION = 'RECOMMENDATION',
}